version: '3.8'
services:
  library_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

    env_file:
      - ./library_back/.env

  library_back:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["sh", "start.sh"]
    ports:
      - 8000:8000
    env_file:
      - ./library_back/.env
    depends_on:
      - library_db
  
volumes:
  postgres_db_data: