version: '3.8'
services:
  library_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

    env_file:
      - ./library_back/.env-sample
    networks:
      - library-network


  library_back:
    build:
      context: .
      dockerfile: docker/back.Dockerfile
    command: ["sh", "start.sh"]
    # ports:
    #   - 8000:8000
    env_file:
      - ./library_back/.env-sample
    volumes:
      - ./library_back:/library_back
      - ./library_back/static:/static/
    depends_on:
      - library_db
    networks:
      - library-network


  library_front:
    build:
      context: .
      dockerfile: docker/front.Dockerfile
    volumes:
      - ./library_front:/library_front
    ports:
      - 3000:3000
    networks:
      - library-network
  

  nginx:
    image: nginx
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./library_back/static:/static/
    ports:
        - "82:82"
    depends_on:
      - library_back
    networks:
      - library-network


volumes:
  postgres_db_data:


networks:
  library-network:
    name: library-network
    driver: bridge