version: '3.8'
services:
  library_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
volumes:
  library_db:
    driver: local