version: '3.8'
services:
  library_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

    env_file:
      - ./library_back/.env


  library_back:
    build:
      context: .
      dockerfile: docker/back.Dockerfile
    command: ["sh", "start.sh"]
    ports:
      - 8000:8000
    env_file:
      - ./library_back/.env
    volumes:
      - ./library_back:/library_back
    depends_on:
      - library_db


  library_front:
    build:
      context: .
      dockerfile: docker/front.Dockerfile
    volumes:
      - ./library_front:/library_front
    command: ["npm", "start"]
    ports:
      - 3000:3000
    depends_on:
      - library_db
  
volumes:
  postgres_db_data: